title: '{{ dev.notes }}'
description: 'dev.notes.filter(note => note.toShare)'
google_analytics: UA-68233507-1

include: ['_pages']

permalink: /:categories/:year/:month/:day/:title

author:
  name: 'JIM KIM'
  description: 'Frontend developer @Melbourne, AU'
  email: jkim.au@gmail.com
  github: https://github.com/jkimau
  linkedin: https://www.linkedin.com/in/jimkimau/

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
